name = "cf-worker-ws-dev"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "7c8b36aa-135e-41be-9d18-6d7d88d0d59b"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
